version: "3.5"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - db
      - mail
    ports:
      - "8069:8069"
      
  db:
    container_name: db
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo

  mail:
    container_name: mail
    image: schickling/mailcatcher
    ports:
      - "1080:1080"

networks:
  default:
    name: odoo_network
