version: 2
jobs:
 build_and_test:
   docker:
     - image: circleci/python:latest
   steps:
     - checkout
     - setup_remote_docker
     - run:
        name: Pull submodule
        command: |
          git submodule init
          git submodule update
     - run:
        name: Start container
        command: |
          docker-compose up -d --build
          docker-compose ps
     - run:
         name: Install dockerize
         command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
         environment:
           DOCKERIZE_VERSION: v0.3.0
     - run:
         name: Wait for db
         command: dockerize -wait tcp://db:5432 -timeout 1m
     - run:
        name: Run tests
        command: |
          echo "Start test...."
          mkdir -p ./tmp/test-results
          docker-compose run web run_test.sh |& tee ./tmp/test-results/output.txt
          echo "Test are done"
     - store_test_results:
        path: ./tmp/test-results
workflows:
 version: 2
 build_and_test:
   jobs:
     - build_and_test
